<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="8" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2017-12-17T14:52:35Z" name="Sequential" finished-at="2017-12-17T14:52:37Z" duration-ms="2081">
    <groups>
      <group name="group2">
        <method signature="HttpBinRedirectTest.testResponseHeadersDefault()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" name="testResponseHeadersDefault" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInParameters1()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" name="testResponseHeadersInParameters1" class="Httpbin.HttpBinRedirectTest"/>
      </group> <!-- group2 -->
      <group name="group1">
        <method signature="HttpBinHeadersTest.testGetDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" name="testGetDefaultBodyResponse" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetHeaders()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" name="testGetHeaders" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetInvalidUrl()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" name="testGetInvalidUrl" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInvalidMethod()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" name="testResponseHeadersInvalidMethod" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinStatusCodeTest.testErrorsMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@3ce1e309]" name="testErrorsMethod" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testOkMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@3ce1e309]" name="testOkMethod" class="Httpbin.HttpBinStatusCodeTest"/>
      </group> <!-- group1 -->
    </groups>
    <test started-at="2017-12-17T14:52:35Z" name="Sequential tests" finished-at="2017-12-17T14:52:37Z" duration-ms="2081">
      <class name="Httpbin.HttpBinRedirectTest">
        <test-method signature="testResponseHeadersDefault()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" started-at="2017-12-17T17:52:36Z" name="testResponseHeadersDefault" finished-at="2017-12-17T17:52:36Z" duration-ms="159" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Response code] expected:
<200>
 but was:
<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Response code] expected:
<200>
 but was:
<404>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersDefault(HttpBinRedirectTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersDefault -->
        <test-method signature="testResponseHeadersInParameters1()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" started-at="2017-12-17T17:52:36Z" name="testResponseHeadersInParameters1" finished-at="2017-12-17T17:52:36Z" duration-ms="274" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Response code] expected:
<200>
 but was:
<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Response code] expected:
<200>
 but was:
<404>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInParameters1(HttpBinRedirectTest.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInParameters1 -->
        <test-method signature="testResponseHeadersInvalidMethod()[pri:0, instance:Httpbin.HttpBinRedirectTest@7334aada]" started-at="2017-12-17T17:52:36Z" name="testResponseHeadersInvalidMethod" finished-at="2017-12-17T17:52:37Z" duration-ms="267" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Response code] expected:
<200>
 but was:
<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Response code] expected:
<200>
 but was:
<404>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInvalidMethod(HttpBinRedirectTest.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInvalidMethod -->
      </class> <!-- Httpbin.HttpBinRedirectTest -->
      <class name="Httpbin.HttpBinStatusCodeTest">
        <test-method signature="testErrorsMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@3ce1e309]" started-at="2017-12-17T17:52:35Z" name="testErrorsMethod" finished-at="2017-12-17T17:52:36Z" duration-ms="556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorsMethod -->
        <test-method signature="testOkMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@3ce1e309]" started-at="2017-12-17T17:52:36Z" name="testOkMethod" finished-at="2017-12-17T17:52:36Z" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOkMethod -->
      </class> <!-- Httpbin.HttpBinStatusCodeTest -->
      <class name="Httpbin.HttpBinHeadersTest">
        <test-method signature="testGetDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" started-at="2017-12-17T17:52:35Z" name="testGetDefaultBodyResponse" finished-at="2017-12-17T17:52:35Z" duration-ms="392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDefaultBodyResponse -->
        <test-method signature="testGetHeaders()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" started-at="2017-12-17T17:52:35Z" name="testGetHeaders" finished-at="2017-12-17T17:52:35Z" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetHeaders -->
        <test-method signature="testGetInvalidUrl()[pri:0, instance:Httpbin.HttpBinHeadersTest@479d31f3]" started-at="2017-12-17T17:52:35Z" name="testGetInvalidUrl" finished-at="2017-12-17T17:52:35Z" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetInvalidUrl -->
      </class> <!-- Httpbin.HttpBinHeadersTest -->
    </test> <!-- Sequential tests -->
  </suite> <!-- Sequential -->
</testng-results>
